language: cpp

matrix:
  include:
    - name: macOS 10.13 Xcode 9.4.1 wx 2.8
      os: osx
      osx_image: xcode9.4
      env:
        - WXVER=2.8


addons:
  apt:
    update: true
    packages:
      - libgtk2.0-dev
      - libwxgtk3.0-dev
      - libboost-dev

install:
  - |
    if [ "$TRAVIS_DIST" == "bionic" ]
    then
      sudo apt-get update
      sudo apt-get install -y --no-install-suggests --no-install-recommends \
        libgtk2.0-dev libwxgtk3.0-dev libboost-dev
    elif [ "$TRAVIS_OS_NAME" == "osx" ]
    then
      curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
      source ./macports-ci install
      sudo port -kN install gsed wxgtk-$WXVER pkgconfig curl
    fi

before_script:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]
    then
      cd $HOME
      curl -LO https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz
      tar xf boost_1_70_0.tar.gz
      cd $OLDPWD
      CFG_ARGS="--prefix=/opt/local --with-boost=$HOME/boost_1_70_0
                --with-wx-config=/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxGTK/$WXVER/bin/wx-config"
      if [ "$WXVER" == 3.0 ]
      then
        gsed -i 's/gtk+-2.0/gtk+-3.0/g' configure*
      fi
    fi
  - touch * && ./configure $CFG_ARGS

script:
  - make -j3
  - if [ -z "$NOCHECK" ]; then make -j3 check; fi
  - sudo make install 
  - ls /opt/local
